src/main/java/core/ChoiceInputValidator.java, src/main/java/core/ChoiceState.java, src/main/java/interfaces/State.java, src/main/java/menus/options/ChangeOptionsState.java, src/main/java/options/ChangeOptionsState.java, src/main/java/options/Options.java
The changeOptionsState is a work in progress. This PR is for choiceState which will be used in many other functions.
=> Feature 10 options

.gitignore
=> Fixgitignore

src/main/java/menus/PauseMenuManager.java
See title, also removed an unused import from PauseMenuManager.
=> Refactored Subclasses of StateManager

src/main/java/game/Shell.java, src/main/java/playercreation/PlayerCreatorManager.java, src/main/java/playercreation/states/PlayerQuestionState.java
=> Shell uses playerCreationManager as starting manager

src/main/java/game/Shell.java, src/main/java/io/InputHandlerImpl.java, src/main/java/io/Output.java, src/main/java/io/OutputHandlerImpl.java, src/main/java/menus/options/ChangeOptionsState.java, src/main/java/playercreation/states/PlayerConfirmState.java, src/main/java/playercreation/states/PlayerQuestionState.java
1) Added text to options. This shouldn't be here but I messed up the branch and don't want to redo all the refactoring work
2) Refactored OutputHandler to Output
=> Output refactoring and options text

src/main/java/objects/battle/enemy/ai/EnemyActionHandler.java, src/main/java/objects/battle/enemy/ai/EnemyPotionHandler.java, src/main/java/objects/battle/enemy/ai/EnemySkillHandler.java, src/main/java/objects/battle/enemy/gimmick/GimmickStrategy.java, src/main/java/objects/battle/enemy/gimmick/StatGimmickStrategy.java, src/main/java/objects/character/BossFacade.java, src/main/java/objects/character/EnemyFighter.java, src/test/java/battle/enemy/ai/EnemyActionHandlerTest.java, src/test/java/battle/enemy/gimmick/StatGimmickStrategyTest.java
I added the text so that the useAction and useGimmick now returns the String so the controller or State class can call enemy.enemyAction().useAction() in their class. This is because controller or State would not know what gimmick the boss used or what action the enemy took.
=> adding text to the classes

src/main/java/battlestates/BattleStateManager.java, src/main/java/battlestates/states/EnemyTurnState.java, src/main/java/battlestates/states/LoseBattleState.java, src/main/java/battlestates/states/UserTurnState.java, src/main/java/battlestates/states/WinBattleState.java, src/main/java/objects/battle/PlayerSkillHandler.java, src/main/java/objects/battle/StatDisplayer.java
=> 98 fixing the bug with battle system

src/main/java/game/Shell.java, src/main/java/switch_managers/SwitchEventType.java
if the switch event end_game is sent, then ends the game.
=> end the game

src/main/java/menus/PauseMenuChoiceStateFactory.java, src/main/java/menus/PauseMenuManager.java, src/main/java/menus/options/ChangeOptionsState.java, src/test/java/menus/PauseMenuManagerTest.java, src/test/java/menus/options/ChangeOptionsStateTest.java
fix all warnings in menu package
=> change quit command to "return"

src/main/java/quests/PlayersStatistics.java, src/main/java/quests/Quest.java, src/main/java/quests/Reward.java, src/main/java/quests/StatisticalReward.java, src/main/java/quests/StatisticalTask.java, src/main/java/quests/Task.java
Created all the entities composing a quest (quest, task & rewards).
* Quest object handles the creation of a quest, checking whether it is completed or not, reward distributed to the player.
* Reward (abstract class – to enable the creation of different type of tasks) & a specific type of reward adding an amount to one of the player's stats.
* Task (abstract class – to enable the creation of different type of tasks) & a specific type of tasks that required to have an exact or a minimum amount in one of the player's tasks.
=> feature 6 - quests entity

src/main/java/objects/battle/enemy/EnemyInfo.java, src/main/java/objects/battle/enemy/ai/DefaultAI.java, src/main/java/objects/battle/enemy/ai/EnemyAI.java, src/main/java/objects/battle/enemy/ai/EnemyActionHandler.java, src/main/java/objects/battle/enemy/ai/EnemyPotion.java, src/main/java/objects/battle/enemy/ai/EnemyPotionHandler.java, src/main/java/objects/battle/enemy/ai/EnemySkillHandler.java, src/main/java/objects/battle/enemy/ai/SkillHandler.java, src/main/java/objects/battle/enemy/ai/SmartAI.java, src/main/java/objects/battle/enemy/factory/EnemyAIFactory.java, src/main/java/objects/battle/enemy/factory/EnemyFactory.java, src/main/java/objects/battle/enemy/factory/EnemyInfoFactory.java, src/main/java/objects/battle/enemy/gimmick/GimmickStrategy.java, src/main/java/objects/battle/enemy/gimmick/StatGimmickEntity.java, src/main/java/objects/battle/enemy/gimmick/StatGimmickStrategy.java, src/main/java/objects/character/BossFacade.java, src/main/java/objects/character/EnemyFacade.java, src/main/java/objects/character/EnemyFighter.java
=> fixing the warnings

src/main/java/game/Game.java, src/main/java/game/ManagerControllerFactory.java, src/main/java/game/Shell.java, src/main/java/main_menu/states/NewGameState.java
refactored Game, created ManagerControllerFactory to create managerController instead of creating it in Game.java
game now starts from main menu
removed startingController in favor of setting a switch event at the start
=> Refactored Game.java

src/main/java/options/Options.java, src/main/java/save/SaveEntityId.java, src/test/java/options/OptionsTest.java
=> options implements savable entity

src/main/java/quests/Quest.java, src/main/java/quests/StatisticalReward.java, src/main/java/quests/StatisticalTask.java, src/test/java/questSystem/QuestEntityTest.java
Added the test file for the quest entities.
Removed the equality boolean in StatisticalTask as it did not make much sense intuitively.
Corrected most of the warnings raised by IntelliJ
=> feature 6 - quests - entity

src/main/java/game/ManagerControllerFactory.java, src/main/java/playercreation/PlayerCreatorInteractor.java, src/main/java/playercreation/PlayerCreatorManager.java, src/main/java/playercreation/factories/PlayerQuestionStateFactory.java, src/test/java/playercreation/PlayerCreatorInteractorTest.java, src/test/java/playercreation/PlayerCreatorManagerTest.java, src/test/java/switch_managers/handlers/PauseResumeEventHandlerTest.java
Changed PlayerCreatorInteractor and PlayerCreatorManager to take in a Player parameter. Refactored associated classes that utilize either PlayerCreatorInteractor or PlayerCreatorManager so the code can run. Updated testing so it works with the change.
=> PlayerCreatorInteractor Has a Player Parameter

src/main/java/database/factories/EventDataFactory.java, src/main/java/database/factories/QuestDataFactory.java, src/main/java/database/managers/EventDataManager.java, src/main/java/database/managers/QuestDataManager.java, src/main/java/database/objects/QuestData.java, src/main/java/database/objects/QuestGiverEventData.java, src/main/java/game_world/factories/EventFactory.java, src/main/java/game_world/managers/EventManager.java, src/main/java/game_world/objects/events/QuestGiverEvent.java, src/main/resources/AreaDatabase.json, src/main/resources/EventDatabase.json, src/main/resources/QuestDatabase.json
added quest data and quest giver events to be implemented
eva - use the data class and the event to give the event
=> quest data + quest giver event for eva

src/main/java/options/Options.java, src/test/java/options/OptionsTest.java
=> modify savableEntity to be inner class of Options

src/main/java/game/Game.java, src/main/java/game/GameEntities.java, src/main/java/game/ManagerControllerFactory.java
title
methods not tested due to being just creating objects
=> Initialize entities

src/main/java/game/GameEntities.java, src/main/java/game/ManagerControllerFactory.java, src/main/java/game_world/factories/EventFactory.java, src/main/java/game_world/factories/ItemPickUpEventFactory.java, src/main/java/game_world/managers/EventManager.java, src/main/java/game_world/objects/events/ItemPickUpEvent.java, src/test/java/worldgen/AreaManagerTest.java, src/test/java/worldgen/EventManagerTest.java
item pick-up is tested by playing the game.
=> refactor to get inventory from client

src/main/java/objects/battle/enemy/ai/SkillHandler.java, src/main/resources/EnemyDatabase.json, src/main/resources/SkillDatabase.json, src/test/java/battle/enemy/EnemyFactoryTest.java, src/test/java/battle/enemy/ai/EnemyActionHandlerTest.java, src/test/java/battle/enemy/ai/SkillHandlerTest.java, src/test/java/objects/character/EnemyTest.java
I added the tests for test coverage
=> adding the test for test coverage

src/main/java/game/ManagerControllerFactory.java, src/main/java/menus/options/ChangeOptionsStateFactory.java, src/main/java/objects/inventory/Inventory.java, src/main/java/options/Options.java, src/main/java/save/SaveEntityId.java, src/test/java/menus/PauseMenuManagerTest.java, src/test/java/switch_managers/SwitchEventManagerTest.java, src/test/java/switch_managers/handlers/PauseResumeEventHandlerTest.java
=> preparation for making Options not static

src/main/java/menus/MenuStateFactory.java, src/main/java/menus/PauseMenuManager.java, src/main/java/switch_managers/ManagerControllerImpl.java, src/main/java/switch_managers/SwitchEventMediatorImpl.java
=> added documentation

src/main/java/game_world/factories/QuestFactory.java, src/main/java/game_world/objects/events/QuestGiverEvent.java, src/main/java/quests/PlayerQuests.java, src/main/java/quests/Quest.java, src/main/java/quests/QuestInteractor.java, src/main/java/quests/QuestMenuFactory.java, src/main/java/quests/QuestMenuState.java, src/main/java/save/SaveEntityId.java
Created a QuestFactory, will be called in a QuestInteractor (will be added later).
Created a PlayerQuests, which is an entity containing the quests accepted by the player. The PlayerQuests also contains all the method to save PlayerQuests from the SavableEntity interface.
Modified the Quest.SaveQuest.tasksToString to simplify the method.
Remaining to be done: QuestInteractor & QuestMenuState.
=> feature 6 – quest – QuestFactory + PlayerQuests entity

src/main/java/game/ManagerControllerFactory.java, src/main/java/menus/MenuStateFactory.java, src/main/java/menus/PauseMenuManager.java, src/main/java/menus/save/SaveMenuStateFactory.java, src/main/java/save/SaveInteractor.java, src/test/java/menus/PauseMenuManagerTest.java, src/test/java/switch_managers/SwitchEventManagerTest.java, src/test/java/switch_managers/handlers/PauseResumeEventHandlerTest.java
added tests
added documentation
=> Integrated save menu

src/main/java/game/ManagerControllerFactory.java, src/main/java/game_world/managers/AreaManager.java, src/main/java/game_world/managers/AreaUseCase.java, src/main/java/game_world/managers/EventDatabaseInteractor.java, src/main/java/game_world/managers/EventManager.java, src/main/java/game_world/objects/Area.java, src/main/java/game_world/objects/states/DialogueState.java, src/test/java/worldgen/AreaManagerTest.java, src/test/java/worldgen/EventManagerTest.java
- fixed some text about "You decided to no" :skull:
- added clean architecture stuff to eventManager for clean architecture
- implemented textSpeed to dialogue
=> moved entities from area manager to use case

src/main/java/battlestates/BattleChoiceType.java, src/main/java/battlestates/BattleStateManager.java, src/main/java/battlestates/factories/BattleStateFactory.java, src/main/java/battlestates/states/BattleAskingState.java, src/main/java/battlestates/states/BattleMenuState.java, src/main/java/battlestates/states/BattleSkillChoiceState.java, src/main/java/battlestates/states/EnemyTurnState.java, src/main/java/battlestates/states/LoseBattleState.java, src/main/java/objects/battle/BattleEntityInteractor.java
UserTurnState is now split into multiple BattleAskingStates.
BattleMenuState asks for which menu the user wants to enter, i.e. Skills, Inventory, Stats
BattleSkillChoiceState asks for which skill the user wants to use
Inventory is not implemented yet, future PR
Stats are displayed
Working update to previous demo integration.
=> Splitting UserTurnState up into BattleAskingStates

src/main/java/game/ManagerControllerFactory.java, src/main/java/menus/MenuStateFactory.java, src/main/java/menus/PauseMenuManager.java, src/test/java/menus/PauseMenuManagerTest.java, src/test/java/switch_managers/SwitchEventManagerTest.java, src/test/java/switch_managers/handlers/PauseResumeEventHandlerTest.java
=> integrate quest menu with pause menu.

src/main/java/quests/QuestMenuState.java
Changed the output displayed to player in case where the player did not accept a single quest yet.
=> Quests – Changed the QuestMenuState in case player does not have quests.

src/main/java/io/InputHandlerImpl.java, src/main/java/menus/save/SaveMenuState.java, src/main/java/playercreation/input_validators/PlayerDescriptionValidator.java, src/main/java/playercreation/input_validators/PlayerNameValidator.java, src/test/java/core/ChoiceInputValidatorTest.java, src/test/java/playercreation/input_validators/PlayerDescriptionValidatorTest.java, src/test/java/playercreation/input_validators/PlayerNameValidatorTest.java
added test for choice input validator
trimmed input and accordingly got rid of isBlank
=> fixed input case-sensitive bug

src/main/java/main_menu/states/NewGameState.java
Fixed an error causing a new game to start even if the user returns to the main menu.
=> Bugfix for New Game Error

src/main/java/objects/character/Bystander.java, src/main/java/objects/character/Character.java, src/main/java/objects/character/Player.java
Title, docstrings for Player, Character and Bystander were edited.
=> Changed docstrings for associated files to be more consistent.

src/main/java/database/factories/QuestDataFactory.java, src/main/java/database/factories/QuestGiverEventFactory.java, src/main/java/database/managers/QuestDataManager.java, src/main/java/database/objects/QuestData.java, src/main/java/database/objects/QuestGiverEventData.java, src/main/java/game_world/objects/events/QuestGiverEvent.java, src/main/java/quests/Quest.java, src/main/java/quests/QuestInteractor.java, src/main/java/quests/QuestMenuFactory.java, src/test/java/questSystem/QuestDatabaseTest.java, src/test/java/questSystem/QuestGiverEventTest.java
Added two testing files for the QuestSystem: QuestDatabaseTest and QuestGiverEventTest.
Made changes to files of the Quest System to fix some warnings pointed out by IntelliJ.
=> Feature 6 – Quest System – Added Testing + Documentation + Fixed IntelliJ warnings

src/main/java/game/ManagerControllerFactory.java, src/main/java/game_world/factories/AreaFactory.java, src/main/java/game_world/managers/AreaDatabaseInteractor.java, src/main/java/game_world/managers/EventDatabaseInteractor.java, src/main/java/game_world/managers/EventManager.java, src/main/java/game_world/objects/Location.java, src/test/java/save/SaveInteractorTest.java, src/test/java/worldgen/AreaManagerTest.java, src/test/java/worldgen/EventManagerTest.java
getEventsFromArea was moved from EventManager to EventDatabaseInteractor. 
Now many dependencies were unneeded and removed.
=> remove unneeded dependencies

src/main/java/core/ChoiceInputValidator.java, src/main/java/core/ChoiceState.java, src/main/java/core/State.java, src/main/java/core/StateManager.java, src/main/java/core/switch_managers/ManagerControllerImpl.java, src/main/java/pause_menu/quests/QuestMenuState.java
Fix warnings in pause_menu and core packages
=> Refactoring

src/main/java/quests/QuestInteractor.java, src/main/java/quests/entities/PlayerQuests.java, src/main/java/quests/entities/Quest.java, src/main/java/quests/use_cases/StatisticalTask.java, src/test/java/quests/QuestEntityTest.java
Removed all the warning for the Quest System.
Moved method to complete a quest from Quest to QuestInteractor.
=> Quest System – Quest System
